# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/eastside-eng/alienswarm

    steps:
      - checkout
      - run: sudo apt-get install software-properties-common
      - run: sudo add-apt-repository ppa:masterminds/glide -y
      - run: sudo apt-get update
      - run: sudo apt-get install glide -y
      - run: glide install
      - run: make bench
      - run: make dist
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` dist/
